### ISSUE TITLE
Grafana 6: please release 0.1.4

### ISSUE THREAD

**Issue by daenney** [cloudflare/cloudflare-grafana-app#11]
With Grafana 6 the Cloudflare app is now broken. This was fixed by Grafana authors in #9. That same fix is also the fix for #10.

Please release 0.1.4 on Grafana.com.

**Comment by daenney** [comment]
Ping @vavrusa

**Comment by Ryonez** [comment]
@vavrusa Can the update be pushed please? No point doing updates if people can't use them.

**Comment by vavrusa** [comment]
Sorry for the wait, I pushed the update PR in https://github.com/grafana/grafana-plugin-repository/pull/391

**Comment by daenney** [comment]
Thank you!

**Comment by Ryonez** [comment]
Cheers
