### ISSUE TITLE
Compatibility with new API Tokens

### ISSUE THREAD

**Issue by msapelov** [cloudflare/cloudflare-grafana-app#14]
They're generally available now, so it's much better to use restricted API Token rather than old root-only API keys.

https://blog.cloudflare.com/api-tokens-general-availability/

**Comment by Aracki** [comment]
Yep, it's probably not a good idea to leave the root API key in Grafana. 👍

**Comment by AndrewFarley** [comment]
+5000, would never put a root API key on Grafana, this app is useless without this imnsho

**Comment by benjick** [comment]
Any news on this?

**Comment by janikrabe** [comment]
The next version will support for both API tokens and API keys.
