### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by dnoya** [cloudflare/cloudflare-grafana-app#18]
Hi I have installed the plugin but I can not make it work.
When Zone board I get this error in the console " `{"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6103,"message":"Invalid format for X-Auth-Key header"}]}],"messages":[],"result":null}`

I have a business account in cloud fare and using the version 0.1.4

Can you please help me ?

Thanks

**Comment by Phara0h** [comment]
Ditto have an enterprise account

**Comment by billabongrob** [comment]
Same on enterprise.

**Comment by janik-cloudflare** [comment]
Closing this in favor of #14. Support for tokens will be added soon.
