### ISSUE TITLE
Cloudflare Plugin is not  appearing in Grafana plugins configuration   

### ISSUE THREAD

**Issue by k-nuhdim** [cloudflare/cloudflare-grafana-app#26]
**What?**
We've installed Cloudflare plugin on Grafana which is not visible in Gragana/plugin configuration.

**When It happens?**
The issue is started after the upgradation of Grafana from v6 to v7

**How we installed the plugins?**
Grafana is running as a docker & we are using a volume as /var/grafana/plugins, As per official installation instruction we have downloaded the plugins and unzip to this plugin directory & restart grafana container 

error logs?
Not seeing any error on  Grafama logs.

Any other observation?
 We can see older cloudflare datastore on grafana but its throwing below error while clicking on it 
 **Plugin not found, no installed plugin with that id"**

**Comment by janik-cloudflare** [comment]
I think this is likely because the plugin wasn't signed prior to v0.2.1. Could you try again with the signed [cloudflare-grafana-app-0.2.1.zip](https://github.com/cloudflare/cloudflare-grafana-app/releases/tag/v0.2.1) please?
