### ISSUE TITLE
Update grafana/plugins/cloudflare-app

### ISSUE THREAD

**Issue by davidholsgrove** [cloudflare/cloudflare-grafana-app#33]
Can the new plugin version be released to https://grafana.com/grafana/plugins/cloudflare-app?

**Comment by davidholsgrove** [comment]
@janik-cloudflare 

The published app is still at `0.1.4` - can we get the `0.2.1` or the next `0.2.2` release uploaded to use in `prometheus-operator/grafana` plugin install flow?

**Comment by janik-cloudflare** [comment]
Hi @davidholsgrove! We have a pull request open at grafana/grafana-plugin-repository#813.
