### ISSUE TITLE
Plugin is unsigned

### ISSUE THREAD

**Issue by GrzegorzMatuszakTSH** [cloudflare/cloudflare-grafana-app#34]
**Description**
I want to test this plugin. But I got an error:
```
Grafana Labs checks each plugin to verify that it has a valid digital signature. Plugin signature verification is part of our security measures to ensure plugins are safe and trustworthy.Grafana Labs can’t guarantee the integrity of this unsigned plugin. Ask the plugin author to request it to be signed.

 Read more about plugins signing
 
```
Link from the message: https://grafana.com/docs/grafana/latest/plugins/plugin-signatures/

![image](https://user-images.githubusercontent.com/43738503/107753265-2316a600-6d20-11eb-96b8-2b3331c25984.png)

**Steps to reproduce:**

- Download repo
- Run `make run`
- Go to plugin settings

**Expected behavior**

The plugin is signed. People can use this plugin without errors.

**Comment by janik-cloudflare** [comment]
Hi @GrzegorzMatuszakTSH! [Releases](https://github.com/cloudflare/cloudflare-grafana-app/releases) will be signed from now on, starting with v0.2.1, which should be [published](https://grafana.com/grafana/plugins/cloudflare-app) soon.

**Comment by GrzegorzMatuszakTSH** [comment]
@janik-cloudflare I set up everything from scratch, but the problem still exists:
![image](https://user-images.githubusercontent.com/43738503/110312766-cf893680-8005-11eb-9595-bbd75d9c6215.png)

**Comment by janik-cloudflare** [comment]
@GrzegorzMatuszakTSH, how did you install the plugin? Running "make run" yourself (as in your "steps to reproduce" above) won't produce a signed plugin, but you can download [the latest release](https://github.com/cloudflare/cloudflare-grafana-app/releases) or install v0.2.1 from [Grafana's plugin repository](https://grafana.com/grafana/plugins/cloudflare-app).

**Comment by GrzegorzMatuszakTSH** [comment]
Yes, I used `make run`.
I thought that docker contains ready to run version

**Comment by janik-cloudflare** [comment]
No, sorry, this is no longer possible with versions of Grafana that require plugin signing. I would recommend setting up a real Grafana instance; `make run` is intended mainly for development and testing.

If you check out a clean release tag in git before running `make run`, you could copy `MANIFEST.txt` from that release into `/var/lib/grafana/plugins/cloudflare` (in the container). We don't recommend doing it this way (see the comment in the `README.md`), but it _should_ work.

**Comment by GrzegorzMatuszakTSH** [comment]
I just wanted to do a quick test of this plugin to check if it fulfills our requirements. For production, we won't use docker instance :)

Thank you for this tip. Now I'm able to run it locally.

**Comment by janik-cloudflare** [comment]
Great to hear that! Thanks for the feedback, I'll see if we can make that easier in the future (or at least add these steps to the README).
