### ISSUE TITLE
API Token support issues

### ISSUE THREAD

**Issue by penekk** [cloudflare/cloudflare-grafana-app#36]
I was stoked seeing that https://github.com/cloudflare/cloudflare-grafana-app/pull/31 has been merged into latest versions.

However I can't get it running,
plugin configuration returns a supposedly successful message but the moment I click back on the user it pops a warning:

![image](https://user-images.githubusercontent.com/12582893/108346703-f828c800-71df-11eb-966e-adef21df80d8.png)

Permissions, as recommended in config.html

![image](https://user-images.githubusercontent.com/12582893/108349328-252aaa00-71e3-11eb-941a-e003fd51306d.png)

No data is returned for `DNS Firewall` dashboard and `Zones` one returns a following error:

```
Templating init failed
{"status":400,"statusText":"","data":{"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6103,"message":"Invalid format for X-Auth-Key header"}]}],"messages":[],"result":null}}
```

Currently using Grafana 6.7.3 with plugin 0.2.1

**Comment by penekk** [comment]
Jumped the gun, I took another sip of my coffe and realized that I should expect those forms to be visible (after upgrading manually to the latest version) and realized cached played a trick on me.

**Comment by janik-cloudflare** [comment]
Hi @penekk, sorry for the late reply! DNS Firewall refers to https://www.cloudflare.com/dns/dns-firewall/, which is currently an enterprise feature.
