### ISSUE TITLE
Error when try to configure credential

### ISSUE THREAD

**Issue by h1kkan** [cloudflare/cloudflare-grafana-app#4]
Hi, i've faced with error when try to setup credentials at plugin config page

```
Cloudflare Grafana App version: 0.1.2
Grafana version: 4.3.2 (commit: ed4d170)
```

**Error**

```
DNS points to prohibited IP | api.cloudflare.com | Cloudflare

body{margin:0;padding:0}
Please enable cookies.

Error
1000
Ray ID: 3768b14c8e945759 • 2017-06-29 11:54:42 UTC
        
DNS points to prohibited IP

What happened?
You've requested a page on a website (api.cloudflare.com) that is on the Cloudflare network. Unfortunately, it is resolving to an IP address that is creating a conflict within Cloudflare's system.

What can I do?
If you are the owner of this website:you should login to Cloudflare and change the DNS A records for api.cloudflare.com to resolve to a different IP address.

Cloudflare Ray ID: 3768b14c8e945759
•
Your IP: XXX.XXX.XXX.XXX
•
Performance & security by Cloudflare
 
window._cf_translation = {};
```

**Comment by danigrant** [comment]
This means there's a loop created between Grafana and Cloudflare. To fix, you will need to "grey cloud" your grafana dashboard in the Cloudflare DNS dashboard. (i.e. click on the orange cloud next to the DNS entry for the subdomain hosting your Grafana dashboard).

**Comment by sosintheass** [comment]
Yeah, it's help to solve this issue. I think this should be added in FAQ :)

**Comment by kedare** [comment]
I am having this issue too, I want to keep Grafana behind Cloudflare, there's no other way to fix this issue ?

**Comment by jostrasser** [comment]
Hi, same here.
I also want to keep my Grafana behind Cloudflare. So to disable the Cloudflare proxy function is no solution for many users.

Please bring an update for the plugin. 

Thanks!

**Comment by korsosa** [comment]
The issue is that Grafana proxies the original Cloudflare headers too, which causes conflict in Cloudflare. There are no plans to fix this in Grafana: https://github.com/grafana/grafana/pull/13552

This can be easily solved by stripping the Cloudflare headers in your reverse proxy config. For example in my case I use Nginx and use this config to strip the headers before forwarding the request to the Grafana Docker container:

```
location ~ / {
        proxy_set_header CF-Connecting-IP "";
        proxy_set_header CF-IPCountry "";
        proxy_set_header CF-RAY "";
        proxy_set_header CF-Visitor "";
        proxy_set_header True-Client-IP "";

        proxy_pass http://127.0.0.1:3000;
    }
```
