### ISSUE TITLE
Cloudflare API token reset broken

### ISSUE THREAD

**Issue by mjtrangoni** [cloudflare/cloudflare-grafana-app#40]
Hi @janik-cloudflare,

I was trying this App with Grafana 8.1.1 and the token reset button seems broken for me. Once I put one API Token there, I am not able to change it anymore.

**Comment by bcreager** [comment]
I am having the same issue.  This is causing the plugin to be unusable as I don't add the correct api token

**Comment by sgammon** [comment]
same here

**Comment by sgammon** [comment]
@vavrusa / @janik-cloudflare / @janikrabe / @elithrar / @torkelo / @mattttt

**Comment by janik-cloudflare** [comment]
Sorry for the delay, I was OoO. #42 fixes this for me, but it would be great if someone else could confirm.

I'll try to get the update released this week.
