### ISSUE TITLE
404 - Plugin not functioning

### ISSUE THREAD

**Issue by Hona** [cloudflare/cloudflare-grafana-app#48]
# Opening a Dashboard
`https://grafana.example.dev/api/plugin-proxy/cloudflare-app/with-key/api/v4/zones?status=active&per_page=50`

Has 404 not found:

```
{"message":"Not found"}
```

![image](https://user-images.githubusercontent.com/10430890/138980430-883442d0-6e72-4e3a-b9e5-6ba5d6b18beb.png)

# Updating Config

https://grafana.example.dev/admin/plugins/cloudflare-app?page=config

`404 Not Found`

**Comment by gyoza** [comment]
I am getting the same when I try to install this plugin. We have 5 accounts in this.

**Comment by BrammyS** [comment]
I'm also getting this! ;(

**Comment by locri3n** [comment]
I am getting this as well.

**Comment by bradleyh-ccl** [comment]
Also getting this issue, the data source is not working correctly for me either.   
![image](https://user-images.githubusercontent.com/83129107/147827415-a7b523f3-89ed-42e6-9500-df2844df9b4f.png)

**Comment by inductor** [comment]
Doesn't work for me either

**Comment by janik-cloudflare** [comment]
Hi all, I'm looking into this. In the meantime, it seems to work when using the search at the top (right below the Grafana logo in the top left) to search for the dashboard.

**Comment by locri3n** [comment]
I get a "dashboard not found" message.

**Comment by janik-cloudflare** [comment]
This was a breaking change in Grafana 8, we're on it!

**Comment by leesuttonuk** [comment]
Is this still an known issue @janik-cloudflare as I'm having this issue still on v0.2.4 (Grafana v8.3.6)

**Comment by janik-cloudflare** [comment]
Hi @leesuttonuk, I ran into this issue when using dashboards that had been created in an earlier version. Assuming you haven't modified the dashboards, could you try uninstalling the plugin and deleting them?

**Comment by leesuttonuk** [comment]
Thanks @janik-cloudflare - all seems to be working now! Appreciated

**Comment by locri3n** [comment]
Fantastic. I’m looking forward to trying this plugin out.
Thanks for your efforts!

**Comment by ElanHasson** [comment]
This still is an issue :(

**Comment by janik-cloudflare** [comment]
@ElanHasson there was a breaking change in Grafana 8; please try uninstalling the plugins, deleting the dashboards, then reinstalling it.

**Comment by ElanHasson** [comment]
Thanks @janik-cloudflare this was a new install. Restarting grafana made it works, but it seems I can only see colo response / nxdomain metrics. No stats for requests. Using a pro account.
