### ISSUE TITLE
Issue with multiple accounts/domains

### ISSUE THREAD

**Issue by wingZero21** [cloudflare/cloudflare-grafana-app#7]
Hi,

I have noticed that at the moment when we have got multiple accounts and domains currently that the dashboard does not seem to be displaying all of the zones. 

Is there any type of limit on this and does this actually support larger amounts of domains?

When attempting to change to a different domain it seems to get to a certain point on the list and just gives up.

Currently the max it is showing me is 50 domains.

**Comment by welborn** [comment]
It appears that the cloudflare API allows a maximum of 50 zones per 'page' when making the response. and defaults to return page 1. Possibly looping through each 'page' until you receive no more results and then returning the zones in the fetchZone function would allow for all of the zones to be returned as opposed to the first 50.

https://api.cloudflare.com/#zone-list-zones

**Comment by edgarsbuss** [comment]
I have similar issue

**Comment by janik-cloudflare** [comment]
I believe this is the same as #12.
