### ISSUE TITLE
Invalid API credentials

### ISSUE THREAD

**Issue by gmelillo** [cloudflare/cloudflare-grafana-app#8]
I'm trying to configure the plugin 0.1.3 on a  Grafana v5.4.3 (commit: 6539180) but when I'm saving the credentials I got the following error:

`Invalid API credentials. This app wont work until the credentials are updated.`

If I use the same credentials with curl to test the validity against the CloudFlare API I got no error.

**Comment by Nklya** [comment]
The same for Grafana v6.3.5 and latest plugin (0.1.4)

**Comment by Nklya** [comment]
Resolved.
Looks like you should use `API Keys`, not `API Tokens`.

Plugin field description `API Token` adds a little bit misunderstanding here.

**Comment by koobitor** [comment]
![Screen Shot 2562-09-12 at 08 44 29](https://user-images.githubusercontent.com/747341/64747560-8d2e8880-d539-11e9-820d-109ee0e5d39e.png)
Can you change Label on that input it make user confuse.

**Comment by archon810** [comment]
🤦‍♂️ I just spent half an hour trying to figure out why this wasn't working for this exact reason. Come on, guys, who wouldn't be confused?

![image](https://user-images.githubusercontent.com/469543/67245540-19717c80-f411-11e9-8575-4db34992e66c.png)

**Comment by archon810** [comment]
Is it possible to convert to using tokens instead though? You can't make multiple API keys, and they allow write access.

**Comment by urusha** [comment]
This makes plugin use tokens instead of keys
```
--- dist/plugin.json.orig	2019-11-06 00:00:00.000000000 +0000
+++ dist/plugin.json	2019-11-06 00:00:00.000000000 +0000
@@ -11,8 +11,7 @@
       "method": "GET",
       "url": "https://api.cloudflare.com/client/v4",
       "headers": [
-        {"name": "X-Auth-Key", "content": "{{.SecureJsonData.token}}"},
-        {"name": "X-Auth-Email", "content": "{{.JsonData.email}}"}
+        {"name": "Authorization", "content": "Bearer {{.SecureJsonData.token}}"}
       ]
     }
   ],
```

**Comment by archon810** [comment]
@urusha Maybe you could PR this real quick and see if it gets accepted?

**Comment by urusha** [comment]
@archon810 this breaks x-auth-key auth, so is not correct for PR (which should be compatible with both auth types I guess). The easiest logic is: empty mail - bearer auth, nonempty - x-auth, but this requires more changes.
For now it could be easily applied to a running installation with one command (debian)
```
patch -p1 -d /var/lib/grafana/plugins/cloudflare-app/ << EOF
--- a/dist/plugin.json 2019-11-06 00:00:00.000000000 +0000
+++ b/dist/plugin.json 2019-11-06 00:00:00.000000000 +0000
@@ -11,8 +11,7 @@
       "method": "GET",
       "url": "https://api.cloudflare.com/client/v4",
       "headers": [
-        {"name": "X-Auth-Key", "content": "{{.SecureJsonData.token}}"},
-        {"name": "X-Auth-Email", "content": "{{.JsonData.email}}"}
+        {"name": "Authorization", "content": "Bearer {{.SecureJsonData.token}}"}
       ]
     }
   ],
EOF
```
requires restart of grafana.

**Comment by janik-cloudflare** [comment]
The incorrect label has been changed. Support for API tokens is tracked in #14.
